apiVersion: v1 
kind: Service 
metadata: 
     name: redis 
     namespace: roboshop 
     labels: 
        component: redis 
        project: roboshop 
        tier: database 
spec: 
   selector: 
       component: redis 
       project: roboshop 
       tier: database 
   ports: 
   - protocol: TCP 
     port: 6379 # service port 
     targetPort: 6379 # container port             