apiVersion: autoscaling/v2
kind: HoriZontalPodAutoscalar 
metadata: 
       name: catalogue 
       namespace: roboshop 
       labels: 
          component: catalogue 
          project: roboshop 
          tier: app 
spec: 
    scaleTargetRef: 
          apiVersion: apps/v1 
          kind: deployment 
          name: catalogue 
    minReplicas: 1 
    maxReplicas: {{ .Values.hpa.maxReplicas }}
    metrics:
    - type: Resource 
      resources: 
         name: cpu 
         target: 
            type: Utilization 
            averageUtilization: {{ .Values.hpa.Utilization }}                